//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using SystematicsPortal.Model.Models.Documents.SubDocuments;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace SystematicsPortal.Model.Models.Documents
{


    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class VernacularDocument : DocumentType
    {

        private DocumentVernacularName vernacularNameField;

        private string translationField;

        private string transliterationField;

        private DocumentVernacularUse[] vernacularUsesField;

        
        public DocumentVernacularName VernacularName
        {
            get
            {
                return this.vernacularNameField;
            }
            set
            {
                this.vernacularNameField = value;
            }
        }

        
        public string Translation
        {
            get
            {
                return this.translationField;
            }
            set
            {
                this.translationField = value;
            }
        }

        
        public string Transliteration
        {
            get
            {
                return this.transliterationField;
            }
            set
            {
                this.transliterationField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("VernacularUse", IsNullable = false)]
        public DocumentVernacularUse[] VernacularUses
        {
            get
            {
                return this.vernacularUsesField;
            }
            set
            {
                this.vernacularUsesField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentVernacularName
    {

        private string languageOfOriginField;

        private string regionOfOriginField;

        private string valueField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageOfOrigin
        {
            get
            {
                return this.languageOfOriginField;
            }
            set
            {
                this.languageOfOriginField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string regionOfOrigin
        {
            get
            {
                return this.regionOfOriginField;
            }
            set
            {
                this.regionOfOriginField = value;
            }
        }

        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentVernacularUse
    {

        private LinkedNameType nameField;

        private string appliesToField;

        private ReferenceType[] referencesField;

        private string idField;

        private string georegionOfUseField;

        private string languageOfUseField;

        private string languageOfUseIsoField;

        private System.DateTime addedField;

        private bool addedFieldSpecified;

        private System.DateTime updatedField;

        private bool updatedFieldSpecified;

        
        public LinkedNameType Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        
        public string AppliesTo
        {
            get
            {
                return this.appliesToField;
            }
            set
            {
                this.appliesToField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable = false)]
        public ReferenceType[] References
        {
            get
            {
                return this.referencesField;
            }
            set
            {
                this.referencesField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string georegionOfUse
        {
            get
            {
                return this.georegionOfUseField;
            }
            set
            {
                this.georegionOfUseField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageOfUse
        {
            get
            {
                return this.languageOfUseField;
            }
            set
            {
                this.languageOfUseField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageOfUseIso
        {
            get
            {
                return this.languageOfUseIsoField;
            }
            set
            {
                this.languageOfUseIsoField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addedSpecified
        {
            get
            {
                return this.addedFieldSpecified;
            }
            set
            {
                this.addedFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedSpecified
        {
            get
            {
                return this.updatedFieldSpecified;
            }
            set
            {
                this.updatedFieldSpecified = value;
            }
        }
    }
}