//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using SystematicsPortal.Model.Models.Documents.SubDocuments;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace SystematicsPortal.Model.Models.Documents
{

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ReferenceDocumentDto : DocumentType
    {

        private DocumentReference referenceField;

        private TextType titleField;

        private object titleUnformattedField;

        private ReferenceType parentReferenceField;

        private DocumentField[] fieldsField;

        private DocumentDefinedConcept[] definedConceptsField;

        private object[] citedTaxaField;

        private DocumentKey[] includedKeysField;

        
        public DocumentReference Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        
        public TextType Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        
        public object TitleUnformatted
        {
            get
            {
                return this.titleUnformattedField;
            }
            set
            {
                this.titleUnformattedField = value;
            }
        }

        
        public ReferenceType ParentReference
        {
            get
            {
                return this.parentReferenceField;
            }
            set
            {
                this.parentReferenceField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable = false)]
        public DocumentField[] Fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("DefinedConcept", IsNullable = false)]
        public DocumentDefinedConcept[] DefinedConcepts
        {
            get
            {
                return this.definedConceptsField;
            }
            set
            {
                this.definedConceptsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("CitedTaxon", IsNullable = false)]
        public object[] CitedTaxa
        {
            get
            {
                return this.citedTaxaField;
            }
            set
            {
                this.citedTaxaField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Key", IsNullable = false)]
        public DocumentKey[] IncludedKeys
        {
            get
            {
                return this.includedKeysField;
            }
            set
            {
                this.includedKeysField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentReference
    {

        private string parentIdField;

        private string typeField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentId
        {
            get
            {
                return this.parentIdField;
            }
            set
            {
                this.parentIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentField
    {

        private string typeField;

        private string valueField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentDefinedConcept
    {

        private DocumentDefinedConceptAssociation[] associationsField;

        private string conceptIdField;

        private string nameIdField;

        private string nameFullField;

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Association", IsNullable = false)]
        public DocumentDefinedConceptAssociation[] Associations
        {
            get
            {
                return this.associationsField;
            }
            set
            {
                this.associationsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conceptId
        {
            get
            {
                return this.conceptIdField;
            }
            set
            {
                this.conceptIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nameId
        {
            get
            {
                return this.nameIdField;
            }
            set
            {
                this.nameIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nameFull
        {
            get
            {
                return this.nameFullField;
            }
            set
            {
                this.nameFullField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentDefinedConceptAssociation : TextType
    {

        private string typeField;

        private string directionField;

        private string relatedConceptIdField;

        private string relatedNameIdField;

        private string relatedNameField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relatedConceptId
        {
            get
            {
                return this.relatedConceptIdField;
            }
            set
            {
                this.relatedConceptIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relatedNameId
        {
            get
            {
                return this.relatedNameIdField;
            }
            set
            {
                this.relatedNameIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relatedName
        {
            get
            {
                return this.relatedNameField;
            }
            set
            {
                this.relatedNameField = value;
            }
        }
    }


    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentKeyLine
    {

        private TextType characteristicField;

        private DocumentKeyLineResultText resultTextField;

        private string idField;

        private string linePrefixField;

        
        public TextType Characteristic
        {
            get
            {
                return this.characteristicField;
            }
            set
            {
                this.characteristicField = value;
            }
        }

        
        public DocumentKeyLineResultText ResultText
        {
            get
            {
                return this.resultTextField;
            }
            set
            {
                this.resultTextField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string linePrefix
        {
            get
            {
                return this.linePrefixField;
            }
            set
            {
                this.linePrefixField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentKeyLineResultText : TextType
    {

        private string nameIdField;

        private string otherKeyLineIdField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nameId
        {
            get
            {
                return this.nameIdField;
            }
            set
            {
                this.nameIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string otherKeyLineId
        {
            get
            {
                return this.otherKeyLineIdField;
            }
            set
            {
                this.otherKeyLineIdField = value;
            }
        }
    }
}