////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;

//// 
//// This source code was auto-generated by xsd, Version=4.8.3928.0.
//// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class Document : DocumentType {
    
//    private DocumentVernacularName vernacularNameField;
    
//    private string translationField;
    
//    private string transliterationField;
    
//    private DocumentVernacularUse[] vernacularUsesField;
    
//    /// <remarks/>
//    public DocumentVernacularName VernacularName {
//        get {
//            return this.vernacularNameField;
//        }
//        set {
//            this.vernacularNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string Translation {
//        get {
//            return this.translationField;
//        }
//        set {
//            this.translationField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string Transliteration {
//        get {
//            return this.transliterationField;
//        }
//        set {
//            this.transliterationField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("VernacularUse", IsNullable=false)]
//    public DocumentVernacularUse[] VernacularUses {
//        get {
//            return this.vernacularUsesField;
//        }
//        set {
//            this.vernacularUsesField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DocumentVernacularName {
    
//    private string languageOfOriginField;
    
//    private string regionOfOriginField;
    
//    private string valueField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string languageOfOrigin {
//        get {
//            return this.languageOfOriginField;
//        }
//        set {
//            this.languageOfOriginField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string regionOfOrigin {
//        get {
//            return this.regionOfOriginField;
//        }
//        set {
//            this.regionOfOriginField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string Value {
//        get {
//            return this.valueField;
//        }
//        set {
//            this.valueField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//public partial class TextType {
    
//    private object[] itemsField;
    
//    private string[] textField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("i")]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string[] Text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//public partial class ReferenceType {
    
//    private object[] itemsField;
    
//    private string[] textField;
    
//    private string referenceIdField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("i")]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string[] Text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string referenceId {
//        get {
//            return this.referenceIdField;
//        }
//        set {
//            this.referenceIdField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//public partial class LinkedNameType {
    
//    private object[] iField;
    
//    private string[] textField;
    
//    private string nameFullField;
    
//    private string nameIdField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("i")]
//    public object[] i {
//        get {
//            return this.iField;
//        }
//        set {
//            this.iField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string[] Text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string nameFull {
//        get {
//            return this.nameFullField;
//        }
//        set {
//            this.nameFullField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string nameId {
//        get {
//            return this.nameIdField;
//        }
//        set {
//            this.nameIdField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//public partial class DocumentType {
    
//    private string vernacularIdField;
    
//    private DocumentTypeDocumentClass documentClassField;
    
//    private DocumentTypeSource sourceField;
    
//    private System.DateTime addedField;
    
//    private bool addedFieldSpecified;
    
//    private System.DateTime updatedField;
    
//    private bool updatedFieldSpecified;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string vernacularId {
//        get {
//            return this.vernacularIdField;
//        }
//        set {
//            this.vernacularIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public DocumentTypeDocumentClass documentClass {
//        get {
//            return this.documentClassField;
//        }
//        set {
//            this.documentClassField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public DocumentTypeSource source {
//        get {
//            return this.sourceField;
//        }
//        set {
//            this.sourceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public System.DateTime added {
//        get {
//            return this.addedField;
//        }
//        set {
//            this.addedField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool addedSpecified {
//        get {
//            return this.addedFieldSpecified;
//        }
//        set {
//            this.addedFieldSpecified = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public System.DateTime updated {
//        get {
//            return this.updatedField;
//        }
//        set {
//            this.updatedField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool updatedSpecified {
//        get {
//            return this.updatedFieldSpecified;
//        }
//        set {
//            this.updatedFieldSpecified = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public enum DocumentTypeDocumentClass {
    
//    /// <remarks/>
//    name,
    
//    /// <remarks/>
//    vernacular,
    
//    /// <remarks/>
//    reference,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public enum DocumentTypeSource {
    
//    /// <remarks/>
//    Names_Plants,
    
//    /// <remarks/>
//    Names_Fungi,
    
//    /// <remarks/>
//    Names_NZAC,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DocumentVernacularUse {
    
//    private LinkedNameType nameField;
    
//    private string appliesToField;
    
//    private ReferenceType[] referencesField;
    
//    private string idField;
    
//    private string georegionOfUseField;
    
//    private string languageOfUseField;
    
//    private string languageOfUseIsoField;
    
//    private System.DateTime addedField;
    
//    private bool addedFieldSpecified;
    
//    private System.DateTime updatedField;
    
//    private bool updatedFieldSpecified;
    
//    /// <remarks/>
//    public LinkedNameType Name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string AppliesTo {
//        get {
//            return this.appliesToField;
//        }
//        set {
//            this.appliesToField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable=false)]
//    public ReferenceType[] References {
//        get {
//            return this.referencesField;
//        }
//        set {
//            this.referencesField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string georegionOfUse {
//        get {
//            return this.georegionOfUseField;
//        }
//        set {
//            this.georegionOfUseField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string languageOfUse {
//        get {
//            return this.languageOfUseField;
//        }
//        set {
//            this.languageOfUseField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string languageOfUseIso {
//        get {
//            return this.languageOfUseIsoField;
//        }
//        set {
//            this.languageOfUseIsoField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public System.DateTime added {
//        get {
//            return this.addedField;
//        }
//        set {
//            this.addedField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool addedSpecified {
//        get {
//            return this.addedFieldSpecified;
//        }
//        set {
//            this.addedFieldSpecified = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public System.DateTime updated {
//        get {
//            return this.updatedField;
//        }
//        set {
//            this.updatedField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool updatedSpecified {
//        get {
//            return this.updatedFieldSpecified;
//        }
//        set {
//            this.updatedFieldSpecified = value;
//        }
//    }
//}
