////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;

//// 
//// This source code was auto-generated by xsd, Version=4.8.3928.0.
//// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class Document : DocumentType {
    
//    private DocumentReference referenceField;
    
//    private TextType titleField;
    
//    private object titleUnformattedField;
    
//    private ReferenceType parentReferenceField;
    
//    private DocumentField[] fieldsField;
    
//    private DocumentDefinedConcept[] definedConceptsField;
    
//    private object[] citedTaxaField;
    
//    private DocumentKey[] includedKeysField;
    
//    /// <remarks/>
//    public DocumentReference Reference {
//        get {
//            return this.referenceField;
//        }
//        set {
//            this.referenceField = value;
//        }
//    }
    
//    /// <remarks/>
//    public TextType Title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
    
//    /// <remarks/>
//    public object TitleUnformatted {
//        get {
//            return this.titleUnformattedField;
//        }
//        set {
//            this.titleUnformattedField = value;
//        }
//    }
    
//    /// <remarks/>
//    public ReferenceType ParentReference {
//        get {
//            return this.parentReferenceField;
//        }
//        set {
//            this.parentReferenceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
//    public DocumentField[] Fields {
//        get {
//            return this.fieldsField;
//        }
//        set {
//            this.fieldsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("DefinedConcept", IsNullable=false)]
//    public DocumentDefinedConcept[] DefinedConcepts {
//        get {
//            return this.definedConceptsField;
//        }
//        set {
//            this.definedConceptsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("CitedTaxon", IsNullable=false)]
//    public object[] CitedTaxa {
//        get {
//            return this.citedTaxaField;
//        }
//        set {
//            this.citedTaxaField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("Key", IsNullable=false)]
//    public DocumentKey[] IncludedKeys {
//        get {
//            return this.includedKeysField;
//        }
//        set {
//            this.includedKeysField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DocumentReference {
    
//    private string parentIdField;
    
//    private string typeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string parentId {
//        get {
//            return this.parentIdField;
//        }
//        set {
//            this.parentIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//public partial class LinkedNameType {
    
//    private object[] iField;
    
//    private string[] textField;
    
//    private string nameFullField;
    
//    private string nameIdField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("i")]
//    public object[] i {
//        get {
//            return this.iField;
//        }
//        set {
//            this.iField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string[] Text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string nameFull {
//        get {
//            return this.nameFullField;
//        }
//        set {
//            this.nameFullField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string nameId {
//        get {
//            return this.nameIdField;
//        }
//        set {
//            this.nameIdField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//public partial class ReferenceType {
    
//    private object[] itemsField;
    
//    private string[] textField;
    
//    private string referenceIdField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("i")]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string[] Text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string referenceId {
//        get {
//            return this.referenceIdField;
//        }
//        set {
//            this.referenceIdField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//public partial class TextType {
    
//    private object[] itemsField;
    
//    private string[] textField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("i")]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string[] Text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//public partial class DocumentType {
    
//    private string referenceIdField;
    
//    private DocumentTypeDocumentClass documentClassField;
    
//    private DocumentTypeSource sourceField;
    
//    private System.DateTime addedField;
    
//    private bool addedFieldSpecified;
    
//    private System.DateTime updatedField;
    
//    private bool updatedFieldSpecified;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string referenceId {
//        get {
//            return this.referenceIdField;
//        }
//        set {
//            this.referenceIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public DocumentTypeDocumentClass documentClass {
//        get {
//            return this.documentClassField;
//        }
//        set {
//            this.documentClassField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public DocumentTypeSource source {
//        get {
//            return this.sourceField;
//        }
//        set {
//            this.sourceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public System.DateTime added {
//        get {
//            return this.addedField;
//        }
//        set {
//            this.addedField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool addedSpecified {
//        get {
//            return this.addedFieldSpecified;
//        }
//        set {
//            this.addedFieldSpecified = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public System.DateTime updated {
//        get {
//            return this.updatedField;
//        }
//        set {
//            this.updatedField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool updatedSpecified {
//        get {
//            return this.updatedFieldSpecified;
//        }
//        set {
//            this.updatedFieldSpecified = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public enum DocumentTypeDocumentClass {
    
//    /// <remarks/>
//    name,
    
//    /// <remarks/>
//    vernacular,
    
//    /// <remarks/>
//    reference,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public enum DocumentTypeSource {
    
//    /// <remarks/>
//    Names_Plants,
    
//    /// <remarks/>
//    Names_Fungi,
    
//    /// <remarks/>
//    Names_NZAC,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DocumentField {
    
//    private string typeField;
    
//    private string valueField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string Value {
//        get {
//            return this.valueField;
//        }
//        set {
//            this.valueField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DocumentDefinedConcept {
    
//    private DocumentDefinedConceptAssociation[] associationsField;
    
//    private string conceptIdField;
    
//    private string nameIdField;
    
//    private string nameFullField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("Association", IsNullable=false)]
//    public DocumentDefinedConceptAssociation[] Associations {
//        get {
//            return this.associationsField;
//        }
//        set {
//            this.associationsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string conceptId {
//        get {
//            return this.conceptIdField;
//        }
//        set {
//            this.conceptIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string nameId {
//        get {
//            return this.nameIdField;
//        }
//        set {
//            this.nameIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string nameFull {
//        get {
//            return this.nameFullField;
//        }
//        set {
//            this.nameFullField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DocumentDefinedConceptAssociation : TextType {
    
//    private string typeField;
    
//    private string directionField;
    
//    private string relatedConceptIdField;
    
//    private string relatedNameIdField;
    
//    private string relatedNameField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string direction {
//        get {
//            return this.directionField;
//        }
//        set {
//            this.directionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string relatedConceptId {
//        get {
//            return this.relatedConceptIdField;
//        }
//        set {
//            this.relatedConceptIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string relatedNameId {
//        get {
//            return this.relatedNameIdField;
//        }
//        set {
//            this.relatedNameIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string relatedName {
//        get {
//            return this.relatedNameField;
//        }
//        set {
//            this.relatedNameField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DocumentKey {
    
//    private DocumentKeyLine[] lineField;
    
//    private string keyIdField;
    
//    private string titleField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("Line")]
//    public DocumentKeyLine[] Line {
//        get {
//            return this.lineField;
//        }
//        set {
//            this.lineField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string keyId {
//        get {
//            return this.keyIdField;
//        }
//        set {
//            this.keyIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DocumentKeyLine {
    
//    private TextType characteristicField;
    
//    private DocumentKeyLineResultText resultTextField;
    
//    private string idField;
    
//    private string linePrefixField;
    
//    /// <remarks/>
//    public TextType Characteristic {
//        get {
//            return this.characteristicField;
//        }
//        set {
//            this.characteristicField = value;
//        }
//    }
    
//    /// <remarks/>
//    public DocumentKeyLineResultText ResultText {
//        get {
//            return this.resultTextField;
//        }
//        set {
//            this.resultTextField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string linePrefix {
//        get {
//            return this.linePrefixField;
//        }
//        set {
//            this.linePrefixField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//public partial class DocumentKeyLineResultText : TextType {
    
//    private string nameIdField;
    
//    private string otherKeyLineIdField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string nameId {
//        get {
//            return this.nameIdField;
//        }
//        set {
//            this.nameIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string otherKeyLineId {
//        get {
//            return this.otherKeyLineIdField;
//        }
//        set {
//            this.otherKeyLineIdField = value;
//        }
//    }
//}
