//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using SystematicsPortal.Model.Models.Documents;
using SystematicsPortal.Model.Models.Documents.SubDocuments;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace SystematicsPortal.Model.Models.Documents.Name
{


    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NameDocument : DocumentType
    {

        private DocumentName nameField;

        private string nameFullField;

        private TextType nameFormattedField;

        private TextType nameScientificField;

        private object namePartFormattedField;

        private string orthographyField;

        private string pageField;

        private string yearOfPublicationField;

        private string yearOnPublicationField;

        private DocumentClassification classificationField;

        private string typeLocalityField;

        private string sanctioningAuthorField;

        private string sanctioningPageField;

        private string hybridLinkField;

        private string checkStatusField;

        private ReferenceType nameReferenceField;

        private ReferenceType taxonomyReferenceField;

        private ReferenceType parentReferenceField;

        private LinkedNameType parentField;

        private LinkedNameType currentNameField;

        private LinkedNameType[] synonymsField;

        private LinkedNameType[] siblingsField;

        private LinkedNameType[] subordinatesField;

        private LinkedNameType basionymField;

        private LinkedNameType basedOnField;

        private LinkedNameType blockingField;

        private LinkedNameType anamorphGenusField;

        private ReferenceType anamorphReferenceField;

        private LinkedNameType typeTaxonField;

        private string foreignIdField;

        private LinkedNameType kingdomField;

        private LinkedNameType phylumField;

        private LinkedNameType classField;

        private LinkedNameType orderField;

        private LinkedNameType familyField;

        private LinkedNameType genusField;

        private DocumentAppliedVernacular[] appliedVernacularsField;

        private DocumentBiostatusValue[] biostatusValuesField;

        private DocumentConcept[] conceptsField;

        private DocumentNote[] notesField;

        private DocumentImage[] imagesField;

        private DocumentExternalLink[] externalLinksField;

        private DocumentNomenclaturalStatus[] nomenclaturalStatusValuesField;

        private DocumentHybridData[] hybridisationField;

        private DocumentHyperlinks hyperlinksField;

        private DocumentCollectionObject[] collectionObjectsField;

        private DocumentKey[] inKeysField;

        
        public DocumentName Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        
        public string NameFull
        {
            get
            {
                return this.nameFullField;
            }
            set
            {
                this.nameFullField = value;
            }
        }

        
        public TextType NameFormatted
        {
            get
            {
                return this.nameFormattedField;
            }
            set
            {
                this.nameFormattedField = value;
            }
        }

        
        public TextType NameScientific
        {
            get
            {
                return this.nameScientificField;
            }
            set
            {
                this.nameScientificField = value;
            }
        }

        
        public object NamePartFormatted
        {
            get
            {
                return this.namePartFormattedField;
            }
            set
            {
                this.namePartFormattedField = value;
            }
        }

        
        public string Orthography
        {
            get
            {
                return this.orthographyField;
            }
            set
            {
                this.orthographyField = value;
            }
        }

        
        public string Page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        
        public string YearOfPublication
        {
            get
            {
                return this.yearOfPublicationField;
            }
            set
            {
                this.yearOfPublicationField = value;
            }
        }

        
        public string YearOnPublication
        {
            get
            {
                return this.yearOnPublicationField;
            }
            set
            {
                this.yearOnPublicationField = value;
            }
        }

        
        public DocumentClassification Classification
        {
            get
            {
                return this.classificationField;
            }
            set
            {
                this.classificationField = value;
            }
        }

        
        public string TypeLocality
        {
            get
            {
                return this.typeLocalityField;
            }
            set
            {
                this.typeLocalityField = value;
            }
        }

        
        public string SanctioningAuthor
        {
            get
            {
                return this.sanctioningAuthorField;
            }
            set
            {
                this.sanctioningAuthorField = value;
            }
        }

        
        public string SanctioningPage
        {
            get
            {
                return this.sanctioningPageField;
            }
            set
            {
                this.sanctioningPageField = value;
            }
        }

        
        public string HybridLink
        {
            get
            {
                return this.hybridLinkField;
            }
            set
            {
                this.hybridLinkField = value;
            }
        }

        
        public string CheckStatus
        {
            get
            {
                return this.checkStatusField;
            }
            set
            {
                this.checkStatusField = value;
            }
        }

        
        public ReferenceType NameReference
        {
            get
            {
                return this.nameReferenceField;
            }
            set
            {
                this.nameReferenceField = value;
            }
        }

        
        public ReferenceType TaxonomyReference
        {
            get
            {
                return this.taxonomyReferenceField;
            }
            set
            {
                this.taxonomyReferenceField = value;
            }
        }

        
        public ReferenceType ParentReference
        {
            get
            {
                return this.parentReferenceField;
            }
            set
            {
                this.parentReferenceField = value;
            }
        }

        
        public LinkedNameType Parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }

        
        public LinkedNameType CurrentName
        {
            get
            {
                return this.currentNameField;
            }
            set
            {
                this.currentNameField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Synonym", IsNullable = false)]
        public LinkedNameType[] Synonyms
        {
            get
            {
                return this.synonymsField;
            }
            set
            {
                this.synonymsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Sibling", IsNullable = false)]
        public LinkedNameType[] Siblings
        {
            get
            {
                return this.siblingsField;
            }
            set
            {
                this.siblingsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Subordinate", IsNullable = false)]
        public LinkedNameType[] Subordinates
        {
            get
            {
                return this.subordinatesField;
            }
            set
            {
                this.subordinatesField = value;
            }
        }

        
        public LinkedNameType Basionym
        {
            get
            {
                return this.basionymField;
            }
            set
            {
                this.basionymField = value;
            }
        }

        
        public LinkedNameType BasedOn
        {
            get
            {
                return this.basedOnField;
            }
            set
            {
                this.basedOnField = value;
            }
        }

        
        public LinkedNameType Blocking
        {
            get
            {
                return this.blockingField;
            }
            set
            {
                this.blockingField = value;
            }
        }

        
        public LinkedNameType AnamorphGenus
        {
            get
            {
                return this.anamorphGenusField;
            }
            set
            {
                this.anamorphGenusField = value;
            }
        }

        
        public ReferenceType AnamorphReference
        {
            get
            {
                return this.anamorphReferenceField;
            }
            set
            {
                this.anamorphReferenceField = value;
            }
        }

        
        public LinkedNameType TypeTaxon
        {
            get
            {
                return this.typeTaxonField;
            }
            set
            {
                this.typeTaxonField = value;
            }
        }

        
        public string ForeignId
        {
            get
            {
                return this.foreignIdField;
            }
            set
            {
                this.foreignIdField = value;
            }
        }

        
        public LinkedNameType Kingdom
        {
            get
            {
                return this.kingdomField;
            }
            set
            {
                this.kingdomField = value;
            }
        }

        
        public LinkedNameType Phylum
        {
            get
            {
                return this.phylumField;
            }
            set
            {
                this.phylumField = value;
            }
        }

        
        public LinkedNameType Class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        
        public LinkedNameType Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }

        
        public LinkedNameType Family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }

        
        public LinkedNameType Genus
        {
            get
            {
                return this.genusField;
            }
            set
            {
                this.genusField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("AppliedVernacular", IsNullable = false)]
        public DocumentAppliedVernacular[] AppliedVernaculars
        {
            get
            {
                return this.appliedVernacularsField;
            }
            set
            {
                this.appliedVernacularsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("BiostatusValue", IsNullable = false)]
        public DocumentBiostatusValue[] BiostatusValues
        {
            get
            {
                return this.biostatusValuesField;
            }
            set
            {
                this.biostatusValuesField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Concept", IsNullable = false)]
        public DocumentConcept[] Concepts
        {
            get
            {
                return this.conceptsField;
            }
            set
            {
                this.conceptsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Note", IsNullable = false)]
        public DocumentNote[] Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Image", IsNullable = false)]
        public DocumentImage[] Images
        {
            get
            {
                return this.imagesField;
            }
            set
            {
                this.imagesField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("ExternalLink", IsNullable = false)]
        public DocumentExternalLink[] ExternalLinks
        {
            get
            {
                return this.externalLinksField;
            }
            set
            {
                this.externalLinksField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("NomenclaturalStatus", IsNullable = false)]
        public DocumentNomenclaturalStatus[] NomenclaturalStatusValues
        {
            get
            {
                return this.nomenclaturalStatusValuesField;
            }
            set
            {
                this.nomenclaturalStatusValuesField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("HybridData", IsNullable = false)]
        public DocumentHybridData[] Hybridisation
        {
            get
            {
                return this.hybridisationField;
            }
            set
            {
                this.hybridisationField = value;
            }
        }

        
        public DocumentHyperlinks Hyperlinks
        {
            get
            {
                return this.hyperlinksField;
            }
            set
            {
                this.hyperlinksField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("CollectionObject", IsNullable = false)]
        public DocumentCollectionObject[] CollectionObjects
        {
            get
            {
                return this.collectionObjectsField;
            }
            set
            {
                this.collectionObjectsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Key", IsNullable = false)]
        public DocumentKey[] InKeys
        {
            get
            {
                return this.inKeysField;
            }
            set
            {
                this.inKeysField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentName
    {

        private string namePartField;

        private string canonicalField;

        private bool inCitationField;

        private bool inCitationFieldSpecified;

        private bool misappliedField;

        private bool misappliedFieldSpecified;

        private bool dubiumField;

        private bool dubiumFieldSpecified;

        private bool proParteField;

        private bool proParteFieldSpecified;

        private bool novumField;

        private bool novumFieldSpecified;

        private bool invalidField;

        private bool invalidFieldSpecified;

        private bool illegitimateField;

        private bool illegitimateFieldSpecified;

        private bool autonymField;

        private bool autonymFieldSpecified;

        private bool recombinationField;

        private bool recombinationFieldSpecified;

        private string nomCodeField;

        private string taxonRankField;

        private string taxonRankSortField;

        private bool isAggregateField;

        private bool isAggregateFieldSpecified;

        private bool isAnamorphField;

        private bool isAnamorphFieldSpecified;

        private string nzRelevanceField;

        private string isSuppressedField;

        private string isCurrentField;

        private string isConservedField;

        private string isSuperfluousField;

        private string isNonCodeNameField;

        private string isNomNudumField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string namePart
        {
            get
            {
                return this.namePartField;
            }
            set
            {
                this.namePartField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string canonical
        {
            get
            {
                return this.canonicalField;
            }
            set
            {
                this.canonicalField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool inCitation
        {
            get
            {
                return this.inCitationField;
            }
            set
            {
                this.inCitationField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inCitationSpecified
        {
            get
            {
                return this.inCitationFieldSpecified;
            }
            set
            {
                this.inCitationFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool misapplied
        {
            get
            {
                return this.misappliedField;
            }
            set
            {
                this.misappliedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool misappliedSpecified
        {
            get
            {
                return this.misappliedFieldSpecified;
            }
            set
            {
                this.misappliedFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool dubium
        {
            get
            {
                return this.dubiumField;
            }
            set
            {
                this.dubiumField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dubiumSpecified
        {
            get
            {
                return this.dubiumFieldSpecified;
            }
            set
            {
                this.dubiumFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool proParte
        {
            get
            {
                return this.proParteField;
            }
            set
            {
                this.proParteField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool proParteSpecified
        {
            get
            {
                return this.proParteFieldSpecified;
            }
            set
            {
                this.proParteFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool novum
        {
            get
            {
                return this.novumField;
            }
            set
            {
                this.novumField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool novumSpecified
        {
            get
            {
                return this.novumFieldSpecified;
            }
            set
            {
                this.novumFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool invalid
        {
            get
            {
                return this.invalidField;
            }
            set
            {
                this.invalidField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invalidSpecified
        {
            get
            {
                return this.invalidFieldSpecified;
            }
            set
            {
                this.invalidFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool illegitimate
        {
            get
            {
                return this.illegitimateField;
            }
            set
            {
                this.illegitimateField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool illegitimateSpecified
        {
            get
            {
                return this.illegitimateFieldSpecified;
            }
            set
            {
                this.illegitimateFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool autonym
        {
            get
            {
                return this.autonymField;
            }
            set
            {
                this.autonymField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autonymSpecified
        {
            get
            {
                return this.autonymFieldSpecified;
            }
            set
            {
                this.autonymFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool recombination
        {
            get
            {
                return this.recombinationField;
            }
            set
            {
                this.recombinationField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recombinationSpecified
        {
            get
            {
                return this.recombinationFieldSpecified;
            }
            set
            {
                this.recombinationFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nomCode
        {
            get
            {
                return this.nomCodeField;
            }
            set
            {
                this.nomCodeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string taxonRank
        {
            get
            {
                return this.taxonRankField;
            }
            set
            {
                this.taxonRankField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string taxonRankSort
        {
            get
            {
                return this.taxonRankSortField;
            }
            set
            {
                this.taxonRankSortField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isAggregate
        {
            get
            {
                return this.isAggregateField;
            }
            set
            {
                this.isAggregateField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isAggregateSpecified
        {
            get
            {
                return this.isAggregateFieldSpecified;
            }
            set
            {
                this.isAggregateFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isAnamorph
        {
            get
            {
                return this.isAnamorphField;
            }
            set
            {
                this.isAnamorphField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isAnamorphSpecified
        {
            get
            {
                return this.isAnamorphFieldSpecified;
            }
            set
            {
                this.isAnamorphFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nzRelevance
        {
            get
            {
                return this.nzRelevanceField;
            }
            set
            {
                this.nzRelevanceField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isSuppressed
        {
            get
            {
                return this.isSuppressedField;
            }
            set
            {
                this.isSuppressedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isCurrent
        {
            get
            {
                return this.isCurrentField;
            }
            set
            {
                this.isCurrentField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isConserved
        {
            get
            {
                return this.isConservedField;
            }
            set
            {
                this.isConservedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isSuperfluous
        {
            get
            {
                return this.isSuperfluousField;
            }
            set
            {
                this.isSuperfluousField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isNonCodeName
        {
            get
            {
                return this.isNonCodeNameField;
            }
            set
            {
                this.isNonCodeNameField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isNomNudum
        {
            get
            {
                return this.isNomNudumField;
            }
            set
            {
                this.isNomNudumField = value;
            }
        }
    }


    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentClassification
    {

        private string idField;

        private string valueField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentAppliedVernacular
    {

        private DocumentAppliedVernacularVernacularName vernacularNameField;

        private TextType vernacularUseNoteField;

        private string idField;

        private string languageOfUseIdField;

        private string languageOfUseField;

        private string languageOfUseIsoField;

        private string regionOfUseSchemaField;

        private string regionOfUseField;

        private string addedField;

        private string updatedField;

        
        public DocumentAppliedVernacularVernacularName VernacularName
        {
            get
            {
                return this.vernacularNameField;
            }
            set
            {
                this.vernacularNameField = value;
            }
        }

        
        public TextType VernacularUseNote
        {
            get
            {
                return this.vernacularUseNoteField;
            }
            set
            {
                this.vernacularUseNoteField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageOfUseId
        {
            get
            {
                return this.languageOfUseIdField;
            }
            set
            {
                this.languageOfUseIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageOfUse
        {
            get
            {
                return this.languageOfUseField;
            }
            set
            {
                this.languageOfUseField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageOfUseIso
        {
            get
            {
                return this.languageOfUseIsoField;
            }
            set
            {
                this.languageOfUseIsoField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string regionOfUseSchema
        {
            get
            {
                return this.regionOfUseSchemaField;
            }
            set
            {
                this.regionOfUseSchemaField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string regionOfUse
        {
            get
            {
                return this.regionOfUseField;
            }
            set
            {
                this.regionOfUseField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentAppliedVernacularVernacularName
    {

        private string vernacularIdField;

        private string languageOfOriginField;

        private string languageOfOriginIsoField;

        private string addedField;

        private string updatedField;

        private string valueField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vernacularId
        {
            get
            {
                return this.vernacularIdField;
            }
            set
            {
                this.vernacularIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageOfOrigin
        {
            get
            {
                return this.languageOfOriginField;
            }
            set
            {
                this.languageOfOriginField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageOfOriginIso
        {
            get
            {
                return this.languageOfOriginIsoField;
            }
            set
            {
                this.languageOfOriginIsoField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentBiostatusValue
    {

        private ReferenceType biostatusReferenceField;

        private DocumentBiostatusValueOrigin originField;

        private DocumentBiostatusValueOccurrence occurrenceField;

        private DocumentBiostatusValueGeoregion georegionField;

        private TextType commentField;

        private string idField;

        private string isActiveField;

        private string isFirstRecordField;

        private string addedField;

        private string updatedField;

        
        public ReferenceType BiostatusReference
        {
            get
            {
                return this.biostatusReferenceField;
            }
            set
            {
                this.biostatusReferenceField = value;
            }
        }

        
        public DocumentBiostatusValueOrigin Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }

        
        public DocumentBiostatusValueOccurrence Occurrence
        {
            get
            {
                return this.occurrenceField;
            }
            set
            {
                this.occurrenceField = value;
            }
        }

        
        public DocumentBiostatusValueGeoregion Georegion
        {
            get
            {
                return this.georegionField;
            }
            set
            {
                this.georegionField = value;
            }
        }

        
        public TextType Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isFirstRecord
        {
            get
            {
                return this.isFirstRecordField;
            }
            set
            {
                this.isFirstRecordField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentBiostatusValueOrigin
    {

        private string codeField;

        private string valueField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentBiostatusValueOccurrence
    {

        private string codeField;

        private string valueField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentBiostatusValueGeoregion
    {

        private string schemaField;

        private string valueField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schema
        {
            get
            {
                return this.schemaField;
            }
            set
            {
                this.schemaField = value;
            }
        }

        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentConcept
    {

        private object nameField;

        private object orthographyField;

        private object pageField;

        private ReferenceType accordingToField;

        private object[] keywordsField;

        private DocumentConceptRelatedConcept[] relatedConceptsField;

        private DocumentConceptDescription[] descriptionsField;

        private string idField;

        private string explicitField;

        private System.DateTime addedField;

        private bool addedFieldSpecified;

        private System.DateTime updatedField;

        private bool updatedFieldSpecified;

        
        public object Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        
        public object Orthography
        {
            get
            {
                return this.orthographyField;
            }
            set
            {
                this.orthographyField = value;
            }
        }

        
        public object Page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        
        public ReferenceType AccordingTo
        {
            get
            {
                return this.accordingToField;
            }
            set
            {
                this.accordingToField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Keyword", IsNullable = false)]
        public object[] Keywords
        {
            get
            {
                return this.keywordsField;
            }
            set
            {
                this.keywordsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("RelatedConcept", IsNullable = false)]
        public DocumentConceptRelatedConcept[] RelatedConcepts
        {
            get
            {
                return this.relatedConceptsField;
            }
            set
            {
                this.relatedConceptsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Description", IsNullable = false)]
        public DocumentConceptDescription[] Descriptions
        {
            get
            {
                return this.descriptionsField;
            }
            set
            {
                this.descriptionsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @explicit
        {
            get
            {
                return this.explicitField;
            }
            set
            {
                this.explicitField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addedSpecified
        {
            get
            {
                return this.addedFieldSpecified;
            }
            set
            {
                this.addedFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedSpecified
        {
            get
            {
                return this.updatedFieldSpecified;
            }
            set
            {
                this.updatedFieldSpecified = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentConceptRelatedConcept
    {

        private object relatedTaxonField;

        private string conceptIdField;

        private string directionField;

        private string typeField;

        private string addedField;

        private string updatedField;

        
        public object RelatedTaxon
        {
            get
            {
                return this.relatedTaxonField;
            }
            set
            {
                this.relatedTaxonField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conceptId
        {
            get
            {
                return this.conceptIdField;
            }
            set
            {
                this.conceptIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentConceptDescription
    {

        private object descriptionIconFilenameField;

        private object descriptionTextField;

        private object descriptionUrlField;

        private string idField;

        private string typeField;

        private string languageField;

        private string languageIsoField;

        private string categoryField;

        private System.DateTime addedField;

        private bool addedFieldSpecified;

        private System.DateTime updatedField;

        private bool updatedFieldSpecified;

        
        public object DescriptionIconFilename
        {
            get
            {
                return this.descriptionIconFilenameField;
            }
            set
            {
                this.descriptionIconFilenameField = value;
            }
        }

        
        public object DescriptionText
        {
            get
            {
                return this.descriptionTextField;
            }
            set
            {
                this.descriptionTextField = value;
            }
        }

        
        public object DescriptionUrl
        {
            get
            {
                return this.descriptionUrlField;
            }
            set
            {
                this.descriptionUrlField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageIso
        {
            get
            {
                return this.languageIsoField;
            }
            set
            {
                this.languageIsoField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addedSpecified
        {
            get
            {
                return this.addedFieldSpecified;
            }
            set
            {
                this.addedFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedSpecified
        {
            get
            {
                return this.updatedFieldSpecified;
            }
            set
            {
                this.updatedFieldSpecified = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentNote
    {

        private TextType textField;

        private ReferenceType referenceField;

        private string idField;

        private string typeField;

        private System.DateTime addedField;

        private bool addedFieldSpecified;

        private System.DateTime updatedField;

        private bool updatedFieldSpecified;

        
        public TextType Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        
        public ReferenceType Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addedSpecified
        {
            get
            {
                return this.addedFieldSpecified;
            }
            set
            {
                this.addedFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedSpecified
        {
            get
            {
                return this.updatedFieldSpecified;
            }
            set
            {
                this.updatedFieldSpecified = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentImage
    {

        private string imageURIField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string imageURI
        {
            get
            {
                return this.imageURIField;
            }
            set
            {
                this.imageURIField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentExternalLink
    {

        private object externalFullNameField;

        private string idField;

        private string externalIdField;

        private string sourceField;

        
        public object ExternalFullName
        {
            get
            {
                return this.externalFullNameField;
            }
            set
            {
                this.externalFullNameField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string externalId
        {
            get
            {
                return this.externalIdField;
            }
            set
            {
                this.externalIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentNomenclaturalStatus
    {

        private TextType commentField;

        private ReferenceType referenceField;

        private string idField;

        private string typeField;

        private string isTrueField;

        private System.DateTime addedField;

        private bool addedFieldSpecified;

        private System.DateTime updatedField;

        private bool updatedFieldSpecified;

        
        public TextType Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        
        public ReferenceType Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isTrue
        {
            get
            {
                return this.isTrueField;
            }
            set
            {
                this.isTrueField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addedSpecified
        {
            get
            {
                return this.addedFieldSpecified;
            }
            set
            {
                this.addedFieldSpecified = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedSpecified
        {
            get
            {
                return this.updatedFieldSpecified;
            }
            set
            {
                this.updatedFieldSpecified = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentHybridData
    {

        private string hybridTextField;

        private DocumentHybridDataHybridParentName[] hybridParentNamesField;

        
        public string HybridText
        {
            get
            {
                return this.hybridTextField;
            }
            set
            {
                this.hybridTextField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("HybridParentName", IsNullable = false)]
        public DocumentHybridDataHybridParentName[] HybridParentNames
        {
            get
            {
                return this.hybridParentNamesField;
            }
            set
            {
                this.hybridParentNamesField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentHybridDataHybridParentName
    {

        private string nameFullField;

        private string nameIdField;

        private string prefixTextField;

        private string suffixTextField;

        
        public string NameFull
        {
            get
            {
                return this.nameFullField;
            }
            set
            {
                this.nameFullField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nameId
        {
            get
            {
                return this.nameIdField;
            }
            set
            {
                this.nameIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string prefixText
        {
            get
            {
                return this.prefixTextField;
            }
            set
            {
                this.prefixTextField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string suffixText
        {
            get
            {
                return this.suffixTextField;
            }
            set
            {
                this.suffixTextField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentHyperlinks
    {

        private DocumentHyperlinksHyperlink[] itemsField;

        
        [System.Xml.Serialization.XmlElementAttribute("Hyperlink")]
        public DocumentHyperlinksHyperlink[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentHyperlinksHyperlink
    {

        private object linkUrlField;

        private object captionField;

        private string typeField;

        private string addedField;

        private string updatedField;

        
        public object LinkUrl
        {
            get
            {
                return this.linkUrlField;
            }
            set
            {
                this.linkUrlField = value;
            }
        }

        
        public object Caption
        {
            get
            {
                return this.captionField;
            }
            set
            {
                this.captionField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string added
        {
            get
            {
                return this.addedField;
            }
            set
            {
                this.addedField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentCollectionObject
    {

        private LinkedNameType nameFormattedField;

        private string collectorField;

        private string substrateField;

        private string partAffectedField;

        private DocumentCollectionObjectAssociation associationField;

        private DocumentCollectionObjectCollectionEventRegion[] collectionEventRegionsField;

        private DocumentCollectionObjectImage[] collectionObjectImagesField;

        private string specimenGuidField;

        private string specimenIdField;

        private string accessionNumberField;

        private string collectionAcronymField;

        private string collectionDateISOField;

        private string typeStatusField;

        
        public LinkedNameType NameFormatted
        {
            get
            {
                return this.nameFormattedField;
            }
            set
            {
                this.nameFormattedField = value;
            }
        }

        
        public string Collector
        {
            get
            {
                return this.collectorField;
            }
            set
            {
                this.collectorField = value;
            }
        }

        
        public string Substrate
        {
            get
            {
                return this.substrateField;
            }
            set
            {
                this.substrateField = value;
            }
        }

        
        public string PartAffected
        {
            get
            {
                return this.partAffectedField;
            }
            set
            {
                this.partAffectedField = value;
            }
        }

        
        public DocumentCollectionObjectAssociation Association
        {
            get
            {
                return this.associationField;
            }
            set
            {
                this.associationField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("CollectionEventRegion", IsNullable = false)]
        public DocumentCollectionObjectCollectionEventRegion[] CollectionEventRegions
        {
            get
            {
                return this.collectionEventRegionsField;
            }
            set
            {
                this.collectionEventRegionsField = value;
            }
        }

        
        [System.Xml.Serialization.XmlArrayItemAttribute("Image", IsNullable = false)]
        public DocumentCollectionObjectImage[] CollectionObjectImages
        {
            get
            {
                return this.collectionObjectImagesField;
            }
            set
            {
                this.collectionObjectImagesField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string specimenGuid
        {
            get
            {
                return this.specimenGuidField;
            }
            set
            {
                this.specimenGuidField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string specimenId
        {
            get
            {
                return this.specimenIdField;
            }
            set
            {
                this.specimenIdField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string accessionNumber
        {
            get
            {
                return this.accessionNumberField;
            }
            set
            {
                this.accessionNumberField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string collectionAcronym
        {
            get
            {
                return this.collectionAcronymField;
            }
            set
            {
                this.collectionAcronymField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string collectionDateISO
        {
            get
            {
                return this.collectionDateISOField;
            }
            set
            {
                this.collectionDateISOField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typeStatus
        {
            get
            {
                return this.typeStatusField;
            }
            set
            {
                this.typeStatusField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentCollectionObjectAssociation : LinkedNameType
    {

        private string typeField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentCollectionObjectCollectionEventRegion
    {

        private string georegionField;

        private string georegionSchemaField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string georegion
        {
            get
            {
                return this.georegionField;
            }
            set
            {
                this.georegionField = value;
            }
        }

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string georegionSchema
        {
            get
            {
                return this.georegionSchemaField;
            }
            set
            {
                this.georegionSchemaField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DocumentCollectionObjectImage
    {

        private string imageUrlField;

        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string imageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }
    }
}